### ISSUE TITLE
Upgrade to 2.8

### ISSUE THREAD

**Issue by pearcemichal** [FreezingMoon/Spritify#11]
Any chance of this getting updated to blender 2.8?

**Comment by DreadKnight** [comment]
Yeah, that would be great :3

**Comment by jmattspartacus** [comment]
Not sure if you're still interested in this, but I forked and updated to Blender 2.8 I've verified that it's working and made some other simple changes.
https://github.com/jmattspartacus/blender_spritify

**Comment by DreadKnight** [comment]
@jmattspartacus Great job with this! I've starred and watched, might contribute a bit.
And wow, amazing to hear you're using it on Factorio, seems like such a cool project!
(I'm the indie game dev making Ancient Beast btw)

**Comment by jmattspartacus** [comment]
Sweet! :D I am just making mods for Factorio, but I'm dabbling in a bit of dev myself on the side, when school permits.

**Comment by DreadKnight** [comment]
@jmattspartacus Understood, I thought I might be going overboard. That game sure seems very fun to mod tbh.

**Comment by DeathApocalypse** [comment]
> 
> 
> Any chance of this getting updated to blender 2.8?

done :)
checked everything with blender 2.8.2, everything works just fine.
i made a file proposal with the updated script, but also uploaded separately here: [](https://github.com/DeathApocalypse/blender_spritify_blender2.8)

**Comment by DreadKnight** [comment]
@DeathApocalypse There was another fork that worked for 2.8 already, posted above.
Not sure if Fweeb checks this repo anymore, hmm... maybe too busy with blender.
I'll probably for this as part of https://github.com/FreezingMoon to make sure it will get love.

**Comment by DreadKnight** [comment]
Pfff, my commit from 2 years ago still not merged, it's clear... https://github.com/Fweeb/blender_spritify/pull/10

**Comment by DreadKnight** [comment]
@DeathApocalypse Alright, forked it here https://github.com/FreezingMoon/Spritify
will make sure it's properly maintained and documented from now on, so feel free to set PR, otherwise will see about cherry picking your patch myself pretty soon.

**Comment by DreadKnight** [comment]
There's a PR for this, but it doesn't work for me https://github.com/FreezingMoon/Spritify/pull/12
Hopefully the dude or someone else will fix it, as people already asking for a 2.9 port https://developer.blender.org/T31129#1001392

**Comment by jmattspartacus** [comment]
I never bothered to submit a PR with working 2.8 version because the other PR for it had never been merged. 
I could probably make an update to 2.9 in the next week or two, depending on my schedule. 
Though I had not fixed the wiki link or anything like that for 2.8 either.

**Comment by DreadKnight** [comment]
@jmattspartacus Sounds good to me. There are people requesting this in various places.
Well, it hasn't been merged because this wasn't been maintained anymore, but I recently took over as I said I would one way or the other and I'm very responsive, just not a good coder, so unlikely to do the ports myself, but regardless, will make sure things will get back on track and that the project is in good shape, whatever it takes. Another issue is that the current PR is not working for me and the dude who submitted it didn't respond to my feedback at all. Whatever happens, will keep in mind the blender wiki add-on links.

**Comment by DreadKnight** [comment]
@jmattspartacus Your branch didn't work for me either btw (corrected my other comment), or I would have merged in the code here since this is more popular.

**Comment by jmattspartacus** [comment]
What does your system log say when you install spritify from my branch? It may be because I specified the version in the script to be 2.81 because that was the build I was running on if you're running on just 2.80, it would complain about the version.

**Comment by DreadKnight** [comment]
@jmattspartacus I've tested both the scripts again and your updated one worked fine for me this time (installed and I've also did sprite/gif tests), so will see about merging it and will also invite you to the organization.

The error before was something like this (new screenie @DeathApocalypse 's version, did post on blenderartists about it before but got no proper help)
![type of error](https://user-images.githubusercontent.com/587487/91543812-738f7800-e927-11ea-8d68-21169d52c901.jpg)
