### ISSUE TITLE
FIleNotFound: 'montage' -- OS X 10.10.1

### ISSUE THREAD

**Issue by Phrohdoh** [FreezingMoon/Spritify#4]
![image](http://i.imgur.com/y8QasIe.png)

I do in fact have montage (via ImageMagick) installed:

```
Version: ImageMagick 6.9.0-10 Q16 x86_64 2015-03-09 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: DPC Modules
Delegates (built-in): bzlib freetype jng jpeg ltdl lzma png xml zlib
```

**Comment by Fweeb** [comment]
Out of curiosity (though I suspect it is), is montage in you PATH? That is, when your in a terminal, you don't have to type the full path to the montage binary to run it. You just have to type `montage`, correct?

Also, judging from your screenshot, I'm guessing that you're running Mac OS X. Is that correct, too?

**Comment by Phrohdoh** [comment]
Yes OS X 10.10 (as the title suggest), and yes montage is in my $PATH.

**Comment by Fweeb** [comment]
Ah, my apologies; I'd only skimmed the title. I wonder if the $PATH environment variable isn't being noticed from Blender's embedded Python on Macs. I don't have a Mac to test that theory on, though. If you don't mind, from Blender's integrated Python console, run the following two lines of code:

    import os
    print(os.environ['PATH'])

Is the path that contains montage in the list of directories that gets printed?

**Comment by Phrohdoh** [comment]
You are correct that (for some reason) the embedded Python is not detecting my entire PATH.
The path for montage is `/usr/local/bin/montage`.

PATH: `/Users/thill/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin`
Blender's PATH: `/usr/bin:/bin:/usr/sbin:/sbin`

**Comment by Fweeb** [comment]
After looking into it and asking a bunch of questions of the Blender devs on IRC, it seems that Mac OS X uses different $PATH env variables for programs launched from the icon vs. programs launched from the terminal. If you run Blender from the terminal, your set $PATH should work and the add-on should work just fine. I did a quick hunt on stackexchange that offers [this solution](http://apple.stackexchange.com/questions/51677/how-to-set-path-for-finder-launched-applications).

If I were to try to fix this from within the add-on, I'd need to detect the operating system, and if it's Mac OS X, spawn a shell subprocess to grab the $PATH variable from there. That's pretty hacky, though. I'd like to avoid doing it, if possible.

**Comment by Phrohdoh** [comment]
Okay so this is WONTFIX for non-Terminal launching of Blender?

**Comment by Fweeb** [comment]
For the time being, I regretfully think so. If there's ever a better recommendation for gleaning the proper $PATH variable from within Blender, I'll happily implement it. Alternatively, if any of Python's imaging libraries ever end up working with Python 3, that might be another option worth considering.

**Comment by Fweeb** [comment]
Follow-up here. Another solution seems to be to edit `/private/etc/paths` and add `/opt/local/bin` there. That *should* make montage exist on your global system path.
